apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  serviceName: "{{ include "postgresql.fullname" . }}-headless"
  replicas: {{ .Values.primary.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgresql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.auth.database }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.auth.existingSecret }}"
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.auth.existingSecret }}"
                  key: DB_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: data
              mountPath: "/var/lib/postgresql/data"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.auth.user | default "postgres" }}", "-d", "{{ .Values.auth.database }}"]
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.auth.user | default "postgres" }}"]
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: postgresql
          app.kubernetes.io/instance: {{ .Release.Name }}
        annotations:
          longhorn.io/numberOfReplicas: "{{ .Values.primary.persistence.longhornReplicas | default 1 }}"
      spec:
        accessModes:
          {{- toYaml .Values.primary.persistence.accessModes | nindent 10 }}
        storageClassName: {{ .Values.primary.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.primary.persistence.size }}