# ============================================================
# TASKMANAGER — UMBRELLA VALUES
# Single file to control the entire stack.
# Jenkins overrides image.tag per service on every deploy.
# ============================================================

# Global service account (used by serviceaccount.yaml)
serviceAccount:
  create: true
  name: taskmanager
# ── Frontend ────────────────────────────────────────────────
frontend:
  serviceAccount:
    create: true
    name: taskmanager-frontend
  replicaCount: 3
  image:
    repository: vuthytourn/taskmanager-frontend
    pullPolicy: IfNotPresent
    tag: "sha-712f9c5"
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    className: "nginx"
    host: taskmanager-frontend.vuthytourn.shop
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingressClassName: "nginx"
    tls: []
  env:
    NEXT_PUBLIC_API_URL: "https://taskmanager-backend.vuthytourn.shop"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
# ── Backend ─────────────────────────────────────────────────
backend:
  serviceAccount:
    create: true
    name: taskmanager-backend
  replicaCount: 3
  image:
    repository: vuthytourn/taskmanager-backend
    pullPolicy: IfNotPresent
    tag: "sha-712f9c5"
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "nginx"
    host: taskmanager-backend.vuthytourn.shop
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingressClassName: "nginx"
    tls: []
  env:
    DB_HOST: "taskmanager-postgresql"
    DB_PORT: "5432"
    DB_NAME: "taskdb"
  secretName: taskmanager-postgresql-chart-db-secret
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
# ── PostgreSQL ───────────────────────────────────────────────
postgresql:
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  auth:
    username: "postgres"
    database: "taskdb"
    # existingSecret: "db-secret"
    secretKeys:
      adminPasswordKey: DB_PASSWORD
      userPasswordKey: DB_PASSWORD
  storage:
    size: 5Gi
    storageClass: "longhorn-single"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
